sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    assets:
        extra_stylesheets:
            - bundles/sonatatranslation/css/sonata-translation.css
            - bundles/sonatapage/sonata-page.back.min.css
        extra_javascripts:
            - bundles/sonatapage/sonata-page.back.min.js
    templates:
        layout: '@SonataTranslation/standard_layout.html.twig'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
